const router = require("express").Router();
const solicitud = require("../mia/solicitud");
const auth = require("../mia/auth");
const agentes = require("../mia/agentes");
const empresas = require("../mia/empresas");
const viajeros = require("../mia/viajeros");
const hospedaje = require("../mia/hospedaje");
const impuestos = require("../mia/impuestos");
const reservas = require("../mia/reservas");
const datosFiscales = require("../mia/datosFiscales");
const pagos = require("../mia/pagos");
const credito = require("../mia/credito");
const stats = require("../mia/stats");
const facturas = require("../mia/facturas");
const hoteles = require("../mia/hoteles");
const etiquetas = require("../mia/etiquetas");
const impersonate = require("../mia/impersonate");
const pagar = require("../mia/pagar");
const saldos = require("../mia/saldos");
const pago_proveedor = require("../mia/pago_proveedor");
const utils = require("../mia/utils");
const reservasClient = require("../mia/reservasClient");

router.use("/auth", auth);
router.use("/solicitud", solicitud);
router.use("/agentes", agentes);
router.use("/empresas", empresas);
router.use("/viajeros", viajeros);
router.use("/hospedaje", hospedaje);
router.use("/impuestos", impuestos);
router.use("/reservas", reservas);
router.use("/datosFiscales", datosFiscales);
router.use("/pagos", pagos);
router.use("/credito", credito);
router.use("/stats", stats);
router.use("/hoteles", hoteles);
router.use("/factura", facturas);
router.use("/etiquetas", etiquetas);
router.use("/impersonate", impersonate);
router.use("/pagar", pagar);
router.use("/saldo", saldos);
router.use("/utils", utils);
router.use("/pago_proveedor", pago_proveedor);
router.use("/reservasClient", reservasClient);

module.exports = router;
