const VIAJES_AEREOS = {
  table: "viajes_aereos",
  required: [
    "id_viaje_aereo",
    "id_booking",
    "id_servicio",
    "trip_type",
    "status",
    "payment_status",
    "total",
  ],
  columnas: [
    "id_viaje_aereo",
    "id_booking",
    "id_servicio",
    "trip_type",
    "status",
    "payment_status",
    "aeropuerto_origen",
    "ciudad_origen",
    "aeropuerto_destino",
    "ciudad_destino",
    "regreso_aeropuerto_origen",
    "regreso_ciudad_origen",
    "regreso_aeropuerto_destino",
    "regreso_ciudad_destino",
    "adults",
    "children",
    "infants",
    "subtotal",
    "taxes",
    "fees",
    "total",
    "currency",
    "cancellation_policies",
    "created_at",
    "updated_at",
    "codigo_confirmacion",
  ],
};

const SERVICIOS = {
  required: ["id_servicio", "total", "id_agente"],
  table: "servicios",
  columnas: [
    "id_servicio",
    "impuestos",
    "subtotal",
    "total",
    "otros_impuestos",
    "is_credito",
    "fecha_limite_pago",
    "id_agente",
    "id_empresa",
  ],
};

const ITEMS = {
  required: ["id_item", "total", "fecha_uso", "saldo", "costo_total"],
  table: "items",
  columnas: [
    "id_item",
    "id_catalogo_item",
    "id_factura",
    "total",
    "subtotal",
    "impuestos",
    "is_facturado",
    "fecha_uso",
    "id_hospedaje",
    "costo_total",
    "costo_subtotal",
    "costo_impuestos",
    "saldo",
    "costo_iva",
    "is_ajuste",
    "id_viaje_aereo",
    "id_renta_carro",
  ],
};

const BOOKINGS = {
  required: [
    "id_servicio",
    "check_in",
    "check_out",
    "total",
    "id_solicitud",
    "id_booking",
  ],
  table: "bookings",
  columnas: [
    "id_booking",
    "id_servicio",
    "id_solicitud",
    "check_in",
    "check_out",
    "total",
    "subtotal",
    "impuestos",
    "estado",
    "fecha_pago_proveedor",
    "costo_total",
    "costo_subtotal",
    "costo_impuestos",
    "fecha_limite_cancelacion",
  ],
};
const VUELOS = {
  required: [
    "id_viaje_aereo",
    "id_viajero",
    "airline",
    "airline_code",
    "departure_airport",
    "departure_airport_code",
    "departure_city",
    "departure_country",
    "departure_date",
    "departure_time",
    "arrival_airport",
    "arrival_airport_code",
    "arrival_city",
    "arrival_country",
    "arrival_date",
    "arrival_time",
    "seat_number",
    "seat_location",
  ],
  table: "vuelos",
  columnas: [
    "id_vuelo",
    "id_viaje_aereo",
    "id_viajero",
    "flight_number",
    "airline",
    "airline_code",
    "aircraft",
    "aircraft_code",
    "departure_airport",
    "departure_airport_code",
    "departure_city",
    "departure_country",
    "departure_date",
    "departure_time",
    "arrival_airport",
    "arrival_airport_code",
    "arrival_city",
    "arrival_country",
    "arrival_date",
    "arrival_time",
    "duration",
    "has_stops",
    "stop_count",
    "stops",
    "currency",
    "baggage",
    "amenities",
    "cancellable",
    "refundable",
    "seat_number",
    "seat_location",
    "has_extra_legroom",
    "is_emergency_exit",
    "additional_fee",
    "currency_seat",
    "id_usuario_creador",
    "id_usuario_modifica",
    "created_at",
    "rate_type",
    "comentarios",
    "fly_type",
  ],
};

// HOSPEDAJE
const HOSPEDAJE = {
  required: [
    "id_hospedaje",
    "id_booking",
    "nombre_hotel",
    "noches",
  ],
  table: "hospedajes",
  columnas: [
    "id_hospedaje",
    "id_booking",
    "id_hotel",
    "nombre_hotel",
    "cadena_hotel",
    "codigo_reservacion_hotel",
    "tipo_cuarto",
    "noches",
    "is_rembolsable",
    "monto_penalizacion",
    "conciliado",
    "credito",
    "created_at",
    "updated_at",
    "comments",
    "nuevo_incluye_desayuno",
    "is_facturado",
    "tipo_desayuno",
    "comentario_desayuno",
    "precio_desayuno",
  ],
};

module.exports = { VIAJES_AEREOS, SERVICIOS, BOOKINGS, ITEMS, VUELOS,HOSPEDAJE };
