const VIAJES_AEREOS = {
  table: "viajes_aereos",
  required: [
    "id_viaje_aereo",
    "id_booking",
    "id_servicio",
    "trip_type",
    "status",
    "payment_status",
    "total",
  ],
  id: "id_viaje_aereo",
  columnas: [
    "id_viaje_aereo",
    "id_booking",
    "id_servicio",
    "trip_type",
    "status",
    "payment_status",
    "aeropuerto_origen",
    "ciudad_origen",
    "aeropuerto_destino",
    "ciudad_destino",
    "regreso_aeropuerto_origen",
    "regreso_ciudad_origen",
    "regreso_aeropuerto_destino",
    "regreso_ciudad_destino",
    "adults",
    "children",
    "infants",
    "subtotal",
    "taxes",
    "fees",
    "total",
    "currency",
    "cancellation_policies",
    "created_at",
    "updated_at",
    "codigo_confirmacion",
  ],
};
const SERVICIOS = {
  required: ["id_servicio", "total", "id_agente"],
  table: "servicios",
  id: "id_servicio",
  columnas: [
    "id_servicio",
    "impuestos",
    "subtotal",
    "total",
    "otros_impuestos",
    "is_credito",
    "fecha_limite_pago",
    "id_agente",
    "id_empresa",
  ],
};
const FACTURAS = {
  required: ["id_factura", "fecha_emision", "estado", "usuario_creador"],
  table: "facturas",
  id: "id_factura",
  columnas: [
    "id_factura",
    "fecha_emision",
    "estado",
    "usuario_creador",
    "total",
    "subtotal",
    "impuestos",
    "saldo",
    "id_facturama",
    "rfc",
    "id_empresa",
    "uuid_factura",
    "rfc_emisor",
    "url_pdf",
    "url_xml",
    "id_agente",
    "fecha_vencimiento",
    "is_prepagada",
    "saldo_x_aplicar_items",
  ],
};
const ITEMS = {
  required: ["id_item", "total", "fecha_uso", "saldo", "costo_total"],
  table: "items",
  id: "id_item",
  columnas: [
    "id_item",
    "id_catalogo_item",
    "id_factura",
    "total",
    "subtotal",
    "impuestos",
    "is_facturado",
    "fecha_uso",
    "id_hospedaje",
    "costo_total",
    "costo_subtotal",
    "costo_impuestos",
    "saldo",
    "costo_iva",
    "is_ajuste",
    "id_viaje_aereo",
    "id_renta_carro",
    "estado",
  ],
};
const BOOKINGS = {
  required: [
    "id_servicio",
    "check_in",
    "check_out",
    "total",
    "id_solicitud",
    "id_booking",
  ],
  table: "bookings",
  id: "id_booking",
  columnas: [
    "id_booking",
    "id_servicio",
    "id_solicitud",
    "check_in",
    "check_out",
    "total",
    "subtotal",
    "impuestos",
    "estado",
    "fecha_pago_proveedor",
    "costo_total",
    "costo_subtotal",
    "costo_impuestos",
    "fecha_limite_cancelacion",
  ],
};
const VUELOS = {
  required: [
    "id_viaje_aereo",
    "id_viajero",
    "airline",
    "airline_code",
    "departure_airport",
    "departure_airport_code",
    "departure_city",
    "departure_country",
    "departure_date",
    "departure_time",
    "arrival_airport",
    "arrival_airport_code",
    "arrival_city",
    "arrival_country",
    "arrival_date",
    "arrival_time",
    "seat_number",
    "seat_location",
  ],
  table: "vuelos",
  id: "id_vuelo",
  columnas: [
    "id_vuelo",
    "id_viaje_aereo",
    "id_viajero",
    "flight_number",
    "airline",
    "airline_code",
    "aircraft",
    "aircraft_code",
    "departure_airport",
    "departure_airport_code",
    "departure_city",
    "departure_country",
    "departure_date",
    "departure_time",
    "arrival_airport",
    "arrival_airport_code",
    "arrival_city",
    "arrival_country",
    "arrival_date",
    "arrival_time",
    "duration",
    "has_stops",
    "stop_count",
    "stops",
    "currency",
    "baggage",
    "amenities",
    "cancellable",
    "refundable",
    "seat_number",
    "seat_location",
    "has_extra_legroom",
    "is_emergency_exit",
    "additional_fee",
    "currency_seat",
    "id_usuario_creador",
    "id_usuario_modifica",
    "created_at",
    "rate_type",
    "comentarios",
    "fly_type",
  ],
};
const HOSPEDAJE = {
  required: ["id_hospedaje", "id_booking", "nombre_hotel", "noches"],
  table: "hospedajes",
  id: "id_hospedaje",
  columnas: [
    "id_hospedaje",
    "id_booking",
    "id_hotel",
    "nombre_hotel",
    "cadena_hotel",
    "codigo_reservacion_hotel",
    "tipo_cuarto",
    "noches",
    "is_rembolsable",
    "monto_penalizacion",
    "conciliado",
    "credito",
    "comments",
    "nuevo_incluye_desayuno",
    "is_facturado",
    "tipo_desayuno",
    "comentario_desayuno",
    "precio_desayuno",
  ],
};
const SALDOS_A_FAVOR = {
  required: ["id_agente", "monto", "metodo_pago", "fecha_pago"],
  table: "saldos_a_favor",
  id: "id_saldos",
  columnas: [
    "id_saldos",
    "id_agente",
    "fecha_creacion",
    "saldo",
    "monto",
    "metodo_pago",
    "fecha_pago",
    "concepto",
    "referencia",
    "currency",
    "tipo_tarjeta",
    "comentario",
    "link_stripe",
    "is_facturable",
    "comprobante",
    "activo",
    "ult_digits",
    "numero_autorizacion",
    "banco_tarjeta",
    "is_descuento",
    "is_facturado",
    "monto_facturado",
    "is_devolucion",
  ],
};
const PAGOS = {
  required: ["id_pago", "id_servicio", "fecha_creacion"],
  table: "pagos",
  id: "id_pago",
  columnas: [
    "id_pago",
    "id_servicio",
    "monto_a_credito",
    "responsable_pago_empresa",
    "responsable_pago_agente",
    "fecha_creacion",
    "pago_por_credito",
    "pendiente_por_cobrar",
    "total",
    "subtotal",
    "impuestos",
    "created_at",
    "updated_at",
    "padre",
    "concepto",
    "referencia",
    "fecha_pago",
    "spei",
    "monto",
    "banco",
    "autorizacion_stripe",
    "last_digits",
    "fecha_transaccion",
    "currency",
    "metodo_de_pago",
    "tipo_de_tarjeta",
    "tipo_de_pago",
    "id_empresa",
    "link_pago",
    "id_saldo_a_favor",
    "id_agente",
    "is_facturado",
    "saldo_aplicado",
    "transaccion",
    "monto_transaccion",
    "estado",
    "monto_saldo",
  ],
};
const FACTURAS_PAGOS_Y_SALDOS = {
  required: ["id_factura", "monto"],
  table: "facturas_pagos_y_saldos",
  columnas: ["id_pago", "id_saldo_a_favor", "id_factura", "monto"],
};
const ITEMS_PAGOS = {
  required: ["id_item", "id_pago", "monto"],
  table: "items_pagos",
  columnas: ["id_item", "id_pago", "monto", "id_relacion"],
};
const ITEMS_FACTURAS = {
  required: ["id_item", "id_factura", "monto"],
  table: "items_facturas",
  columnas: ["id_item", "id_factura", "monto", "id_relacion"],
};
module.exports = {
  VIAJES_AEREOS,
  SERVICIOS,
  BOOKINGS,
  ITEMS,
  VUELOS,
  SALDOS_A_FAVOR,
  PAGOS,
  HOSPEDAJE,
  FACTURAS,
  FACTURAS_PAGOS_Y_SALDOS,
  ITEMS_FACTURAS,
  ITEMS_PAGOS,
};
